name: demo-app
image:
  repository: nginx
  tag: latest
replicaCount: 1
altCommand:
  enabled: false
  command: ""
health:
  enabled: true
  path: /
  port: 80
ingress:
  enabled: false
  path: /
http:
  port: 80
  containerPort: 80
  name: http
