---
ingressRoute:
  dashboard:
    matchRule: PathPrefix(`/traefik-dashboard`) || PathPrefix(`/api`)
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
globalArguments:
  - "--api.insecure=true"
