apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        gitCommit: {{ .Values.git_sha }}
    spec:
      imagePullSecrets:
        - name: docker-hub-creds
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          {{- if .Values.altCommand.enabled }}
          command: {{ .Values.altCommand.command }}
          {{- end }}
          ports:
            - name: {{ .Values.http.name }}
              containerPort: {{ .Values.http.containerPort }}
          {{- if .Values.health.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: {{ .Values.health.port }}
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: {{ .Values.health.port }}
            initialDelaySeconds: 2
            periodSeconds: 5
          {{- end }}
