apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - name: {{ .Values.http.name }}
      port: {{ .Values.http.port }}
      targetPort: {{ .Values.http.port }}
  selector:
    app: {{ .Values.name }}
